### PR TITLE
Fix texture downscaling (alternative 2)

### LINKED ISSUE #171: Improve linear_motor.wbt Node hierarchy
**Describe the Bug**
The node hierarchy of the linear motor simulation should be improved. It does contain useless group node and empty transform node.

Furthermore with the AMD radeon R5 the ruler is to much transparent.
Nvidia GTX 980:
linear_motor

Radeon R5:
linear_motor

### PR DESCRIPTION
**Pull request by fabienrohrer**
Fix #171

Do a Gaussian blue while scaling down.

### CODE REVIEW

**Comment by fabienrohrer** [comment]
The algorithm shown in this branch seems to be a good tradeoff.

- it is slightly quicker than the Qt algorithms.
- it solves the alpha alteration visible in `Qt::SmoothTransformation`.
- it solves the alias issues in `Qt::FastTransformation`. The quality is comparable.

Comparison of the low-quality texture mode in master vs this branch:

| world | master | this branch |
| --- | --- | --- |
| `city.wbt` | city_master | city_patch |
| `hoap2_walk` | hoap2_walk_master | hoap2_walk_patch |
| `linear_motor` (buggy on master) | linear_motor_master | linear_motor_patch |

Comparison of the filter quality:

| Filter | Result |
| --- | --- |
| `Qt: FastTransformation` (alias issues) | filter_fast |
| `Qt: SmoothTransformation` (alpha issues) | filter_smooth |
| this branch (ok) | filter_pr |

**Comment by omichel** [comment]
That seems to be a very good compromise indeed.

File: src/webots/maths/WbImage.cpp [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+  {1.0f / 16.0f, 2.0f / 16.0f, 1.0f / 16.0f},
+  {2.0f / 16.0f, 4.0f / 16.0f, 2.0f / 16.0f},
+  {1.0f / 16.0f, 2.0f / 16.0f, 1.0f / 16.0f},
+};
+
+WbImage *WbImage::downscale(int width, int height, int xBlurRadius, int yBlurRadius) {
+  const int dstSize = width * height * mChannels;
+  const int srcSize = mWidth * mHeight * mChannels;
+  unsigned char *pixels = (unsigned char *)malloc(dstSize);
+  memset(pixels, 0, dstSize);
```
Comment (omichel) [inline src/webots/maths/WbImage.cpp]: This is probably useless and CPU time consuming, isn't it?

File: src/webots/maths/WbImage.cpp [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+
+  const float widthRatio = (float)mWidth / width;
+  const float heightRatio = (float)mHeight / height;
+
+  for (int j = 0; j < height; ++j) {
+    for (int i = 0; i < width; ++i) {
+      for (int c = 0; c < mChannels; ++c) {
+        int destIndex = (i + (j * width)) * mChannels + c;
```
Comment (omichel) [inline src/webots/maths/WbImage.cpp]:
```suggestion
        const int destIndex = (i + (j * width)) * mChannels + c;
```

File: src/webots/maths/WbImage.cpp [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+        for (int u = -1; u < 2; ++u) {
+          float x = CLAMP(widthRatio * i + u * xBlurRadius, 0, mWidth - 1);
```
Comment (omichel) [inline src/webots/maths/WbImage.cpp]:
```suggestion
          const float x = CLAMP(widthRatio * i + u * xBlurRadius, 0, mWidth - 1);
```

File: src/webots/maths/WbImage.cpp [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+          for (int v = -1; v < 2; ++v) {
+            float y = CLAMP(heightRatio * j + v * yBlurRadius, 0, mHeight - 1);
```
Comment (omichel) [inline src/webots/maths/WbImage.cpp]:
```suggestion
            const float y = CLAMP(heightRatio * j + v * yBlurRadius, 0, mHeight - 1);
```

File: src/webots/maths/WbImage.cpp [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+            int srcIndex = CLAMP((int)(x + y * mWidth) * mChannels + c, 0, srcSize);
```
Comment (omichel) [inline src/webots/maths/WbImage.cpp]:
```suggestion
            const int srcIndex = CLAMP((int)(x + y * mWidth) * mChannels + c, 0, srcSize);
```

File: src/webots/maths/WbImage.cpp (hunk 1 above)
Comment (fabienrohrer) [reply src/webots/maths/WbImage.cpp]: Yes, but it's not possible to avoid to create the new scaled-down image at some point, and as the following loop increment the elements, I need to initialize it. It's for sure anecdotical relatively to the following loop.

**Comment by fabienrohrer** [comment]
test me

**Comment by fabienrohrer** [comment]
test me

**Comment by fabienrohrer** [comment]
👍

File: src/webots/maths/WbImage.cpp [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+            const float y = CLAMP(heightRatio * j + v * yBlurRadius, 0, mHeight - 1);
+            const int srcIndex = CLAMP((int)(x + y * mWidth) * mChannels + c, 0, srcSize);
+            pixels[destIndex] += (unsigned char)(gaussBlur[u + 1][v + 1] * mData[srcIndex]);
+          }
+        }
+      }
+    }
+  }
+
+  return new WbImage(pixels, width, height, mChannels, true);
```
Comment (omichel) [inline src/webots/maths/WbImage.cpp]: The memory leak is here: we should pass `false` instead of `true`.
